[package]
name = "azalea_grammar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
pest = "2.7.0"
pest_ascii_tree = "0.1.0"
pest_derive = "2.7.0"
